apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: tms-demo
stringData:
  sasl: "plaintext"
  tls: "enable"
  username: "tms-processing-user"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: tms-demo
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: tms-service-endpoint
    key: SASL_PWD
  - parameter: tls
    name: keda-kafka-secrets
    key: tls
  - parameter: ca
    name: tms-processing-cert
    key: ca.pem
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tms-demo-enrichment-scaled
  namespace: tms-demo
spec:
  scaleTargetRef:
    name: tms-demo-enrichment
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount:  10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServersFromEnv: SASL_BOOTSTRAP_SERVERS
        consumerGroup: tms-streams-demo-enrichment
        topic: observations.weather.raw
        lagThreshold: '5'
        scaleToZeroOnInvalidOffset: 'true'
      authenticationRef:
        name: keda-trigger-auth-kafka-credential
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tms-demo-calculations-scaled
  namespace: tms-demo
spec:
  scaleTargetRef:
    name: tms-demo-calculations
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount:  10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServersFromEnv: SASL_BOOTSTRAP_SERVERS
        consumerGroup: tms-streams-demo-calculations
        topic: observations.weather.municipality
        lagThreshold: '5'
        scaleToZeroOnInvalidOffset: 'true'
      authenticationRef:
        name: keda-trigger-auth-kafka-credential
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tms-demo-multivariate-scaled
  namespace: tms-demo
spec:
  scaleTargetRef:
    name: tms-demo-multivariate
  cooldownPeriod: 300
  minReplicaCount: 0
  maxReplicaCount:  10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServersFromEnv: SASL_BOOTSTRAP_SERVERS
        consumerGroup: tms-streams-demo-multivariate
        topic: observations.weather.municipality
        lagThreshold: '5'
        scaleToZeroOnInvalidOffset: 'true'
      authenticationRef:
        name: keda-trigger-auth-kafka-credential