apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: tms-demo
stringData:
  sasl: "plaintext"
  tls: "enable"
  username: "tms-processing-user"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: tms-demo
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: tms-service-endpoint
    key: SASL_PWD
  - parameter: tls
    name: keda-kafka-secrets
    key: tls
  - parameter: ca
    name: tms-processing-cert
    key: ca.pem
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tms-demo-enrichment-scaled
  namespace: tms-demo
spec:
  scaleTargetRef:
    name: tms-demo-enrichment
  minReplicaCount: 1
  maxReplicaCount:  3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 240
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 240
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60
  triggers:
    - type: prometheus
      metadata:
        serverAddress: "http://prometheus-k8s.monitoring:9090"
        query: max by(topic) (kafka_consumer_fetch_manager_records_lag_avg{topic="observations.weather.raw", service="tms-demo-enrichment-svc"})
        threshold: "1000"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tms-demo-calculations-scaled
  namespace: tms-demo
spec:
  scaleTargetRef:
    name: tms-demo-calculations
  minReplicaCount: 1
  maxReplicaCount:  3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 240
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 240
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60
  triggers:
    - type: prometheus
      metadata:
        serverAddress: "http://prometheus-k8s.monitoring:9090"
        query: max by(topic) (kafka_consumer_fetch_manager_records_lag_avg{topic="observations.weather.enriched", service="tms-demo-calculations-svc"})
        threshold: "1000"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tms-demo-multivariate-scaled
  namespace: tms-demo
spec:
  scaleTargetRef:
    name: tms-demo-multivariate
  minReplicaCount: 1
  maxReplicaCount:  3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60
  triggers:
    - type: prometheus
      metadata:
        serverAddress: "http://prometheus-k8s.monitoring:9090"
        query: max by(topic) (kafka_consumer_fetch_manager_records_lag_avg{topic="observations.weather.enriched", service="tms-demo-multivariate-svc"})
        threshold: "1000"
